server:
  port: 8083

spring:
  application:
    name: grievance-service

  datasource:
    url: jdbc:mysql://localhost:3306/grievance_data?createDatabaseIfNotExist=true
    username: root
    password: ravigoud

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
